name: Angular Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name : Install Dependencies
        working-directory: ./angular-workflow-demo-app
        run: npm ci
      - name: Build 
        run: npm run build
      - name: Testing 
        run: npm test